services:
  audiobookup:
    # This line is for end-users. It tells Docker to pull the pre-built image from
    # the GitHub Container Registry. Update the tag to the latest release version.
    image: ghcr.io/ishbuggy/audiobookup:v0.14.0

    # This section is for development. It is ignored unless you run 'docker compose up --build'.
    build:
      context: .
      dockerfile: ./src/dockerfile

    container_name: audiobookup
    ports:
      - "13300:13300"
    environment:
      # Set to your user's ID on the host machine to avoid file permission issues.
      # Find this by running the 'id' command in your server's terminal.
      - PUID=1000
      - PGID=1000
      # Set the timezone for the container itself using a standard IANA name.
      # This should match the timezone you configure in the application's UI.
      # A list of valid timezones can be found here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Etc/UTC
    volumes:
      # --- Persistent User Data ---
      # This section maps folders on your host machine to folders inside the container.
      # For systems like Unraid, you may want to change these to absolute paths
      # (e.g., /mnt/user/appdata/audiobookup/config:/config).

      # Volume for application configuration (settings.json, logs, temp files)
      - ./appdata/config:/config

      # Volume for critical database and Audible authentication files
      - ./appdata/database:/database

      # Volume for your final, converted audiobook files (.m4b)
      - ./audiobooks:/data

    restart: unless-stopped